/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.product.information.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Quantity extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 452141573005742427L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Quantity\",\"namespace\":\"com.product.information.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"long\",\"java-class\":\"java.lang.Long\"}},{\"name\":\"quantityTotal\",\"type\":{\"type\":\"int\",\"java-class\":\"java.lang.Integer\"}},{\"name\":\"quantityAvailable\",\"type\":{\"type\":\"int\",\"java-class\":\"java.lang.Integer\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Quantity> ENCODER =
      new BinaryMessageEncoder<Quantity>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Quantity> DECODER =
      new BinaryMessageDecoder<Quantity>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Quantity> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Quantity> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Quantity> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Quantity>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Quantity to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Quantity from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Quantity instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Quantity fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public int quantityTotal;
  @Deprecated public int quantityAvailable;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Quantity() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param quantityTotal The new value for quantityTotal
   * @param quantityAvailable The new value for quantityAvailable
   */
  public Quantity(java.lang.Long id, java.lang.Integer quantityTotal, java.lang.Integer quantityAvailable) {
    this.id = id;
    this.quantityTotal = quantityTotal;
    this.quantityAvailable = quantityAvailable;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return quantityTotal;
    case 2: return quantityAvailable;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: quantityTotal = (java.lang.Integer)value$; break;
    case 2: quantityAvailable = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'quantityTotal' field.
   * @return The value of the 'quantityTotal' field.
   */
  public int getQuantityTotal() {
    return quantityTotal;
  }


  /**
   * Sets the value of the 'quantityTotal' field.
   * @param value the value to set.
   */
  public void setQuantityTotal(int value) {
    this.quantityTotal = value;
  }

  /**
   * Gets the value of the 'quantityAvailable' field.
   * @return The value of the 'quantityAvailable' field.
   */
  public int getQuantityAvailable() {
    return quantityAvailable;
  }


  /**
   * Sets the value of the 'quantityAvailable' field.
   * @param value the value to set.
   */
  public void setQuantityAvailable(int value) {
    this.quantityAvailable = value;
  }

  /**
   * Creates a new Quantity RecordBuilder.
   * @return A new Quantity RecordBuilder
   */
  public static com.product.information.avro.model.Quantity.Builder newBuilder() {
    return new com.product.information.avro.model.Quantity.Builder();
  }

  /**
   * Creates a new Quantity RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Quantity RecordBuilder
   */
  public static com.product.information.avro.model.Quantity.Builder newBuilder(com.product.information.avro.model.Quantity.Builder other) {
    if (other == null) {
      return new com.product.information.avro.model.Quantity.Builder();
    } else {
      return new com.product.information.avro.model.Quantity.Builder(other);
    }
  }

  /**
   * Creates a new Quantity RecordBuilder by copying an existing Quantity instance.
   * @param other The existing instance to copy.
   * @return A new Quantity RecordBuilder
   */
  public static com.product.information.avro.model.Quantity.Builder newBuilder(com.product.information.avro.model.Quantity other) {
    if (other == null) {
      return new com.product.information.avro.model.Quantity.Builder();
    } else {
      return new com.product.information.avro.model.Quantity.Builder(other);
    }
  }

  /**
   * RecordBuilder for Quantity instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Quantity>
    implements org.apache.avro.data.RecordBuilder<Quantity> {

    private long id;
    private int quantityTotal;
    private int quantityAvailable;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.product.information.avro.model.Quantity.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.quantityTotal)) {
        this.quantityTotal = data().deepCopy(fields()[1].schema(), other.quantityTotal);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.quantityAvailable)) {
        this.quantityAvailable = data().deepCopy(fields()[2].schema(), other.quantityAvailable);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Quantity instance
     * @param other The existing instance to copy.
     */
    private Builder(com.product.information.avro.model.Quantity other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantityTotal)) {
        this.quantityTotal = data().deepCopy(fields()[1].schema(), other.quantityTotal);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.quantityAvailable)) {
        this.quantityAvailable = data().deepCopy(fields()[2].schema(), other.quantityAvailable);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.product.information.avro.model.Quantity.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.product.information.avro.model.Quantity.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantityTotal' field.
      * @return The value.
      */
    public int getQuantityTotal() {
      return quantityTotal;
    }


    /**
      * Sets the value of the 'quantityTotal' field.
      * @param value The value of 'quantityTotal'.
      * @return This builder.
      */
    public com.product.information.avro.model.Quantity.Builder setQuantityTotal(int value) {
      validate(fields()[1], value);
      this.quantityTotal = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantityTotal' field has been set.
      * @return True if the 'quantityTotal' field has been set, false otherwise.
      */
    public boolean hasQuantityTotal() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantityTotal' field.
      * @return This builder.
      */
    public com.product.information.avro.model.Quantity.Builder clearQuantityTotal() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantityAvailable' field.
      * @return The value.
      */
    public int getQuantityAvailable() {
      return quantityAvailable;
    }


    /**
      * Sets the value of the 'quantityAvailable' field.
      * @param value The value of 'quantityAvailable'.
      * @return This builder.
      */
    public com.product.information.avro.model.Quantity.Builder setQuantityAvailable(int value) {
      validate(fields()[2], value);
      this.quantityAvailable = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'quantityAvailable' field has been set.
      * @return True if the 'quantityAvailable' field has been set, false otherwise.
      */
    public boolean hasQuantityAvailable() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'quantityAvailable' field.
      * @return This builder.
      */
    public com.product.information.avro.model.Quantity.Builder clearQuantityAvailable() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Quantity build() {
      try {
        Quantity record = new Quantity();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.quantityTotal = fieldSetFlags()[1] ? this.quantityTotal : (java.lang.Integer) defaultValue(fields()[1]);
        record.quantityAvailable = fieldSetFlags()[2] ? this.quantityAvailable : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Quantity>
    WRITER$ = (org.apache.avro.io.DatumWriter<Quantity>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Quantity>
    READER$ = (org.apache.avro.io.DatumReader<Quantity>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeInt(this.quantityTotal);

    out.writeInt(this.quantityAvailable);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.quantityTotal = in.readInt();

      this.quantityAvailable = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.quantityTotal = in.readInt();
          break;

        case 2:
          this.quantityAvailable = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










